import React from 'react'
import PropTypes from 'prop-types'
import { css } from 'glamor'
import Relative from '../atoms/Relative'

const inputStyle = css({
  position: 'absolute',
  top: 0,
  right: 0,
  bottom: 0,
  left: 0,
  width: '100%',
  opacity: 0.00001,
  pointerEvents: 'none',
})

/**
 * The FileSelector component acts similar to <input type="file" /> but also provides useful tools to manage and display files.
 * The child should be a function which gets in passed following parameters:
 *
 * |Parameter | Type | Description |
 * |----------|:----:|------------:|
 * |`files`|Array<[File](https://developer.mozilla.org/en-US/docs/Web/API/File)>|Array containing added files (originating from [`FileList`](https://developer.mozilla.org/en-US/docs/Web/API/FileList))
 * |`openDialog`|Function|Triggers the browsers file dialog
 * |`getPreview`|Function|Get a preview generated by the browser (only works for images)
 * | `removeFile`|Function|Removes a file from the list
 * |`clear`|Function|Clears all files
 *
 * ```example
 * <ThemeProvider>
 *    <Form onSubmit={(e, data) => console.log(data.images)}>
 *      <FileSelector name="images">
 *        {({ files, openDialog, getPreview, removeFile, clear }) => (
 *          <ul>
 *            {files.map(file => (
 *              <li key={file.name} onClick={() => removeFile(file)}>
 *                <img src={getPreview(file)} height={40} width={40} />
 *                {file.name}
 *              </li>
 *            ))}
 *          </ul>
 *        )}
 *      </FileSelector>
 *    </Form>
 *  </ThemeProvider>
 * ```
 */
export default class FileSelector extends React.Component {
  static propTypes = {
    children: PropTypes.func,
    /** Name of the field which is picked up by <Form> **/
    name: PropTypes.string,
    /** Whether multiple files should be allowed **/
    multiple: PropTypes.bool,
    /** Whether this field is required **/
    required: PropTypes.bool,
    /** Accepted file types. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-accept **/
    accept: PropTypes.string,
  }

  static defaultProps = {
    children: () => {},
  }

  previews = new Map()

  componentWillUnmount() {
    this.clearPreviews()
  }

  state = {
    files: [],
  }

  setInputRef = ref => (this.inputRef = ref)

  handleChange = e => {
    const fileItems = e.dataTransfer ? e.dataTransfer.files : e.target.files
    this.setState(state => ({ files: [...state.files, ...fileItems] }))
  }

  openDialog = () => this.inputRef.click()

  clearPreviews = () => {
    this.previews.forEach(window.URL.revokeObjectURL)
    this.previews.clear()
  }

  clear = () => {
    this.clearPreviews()
    this.setState({ files: [] })
  }

  removeFile = file => {
    const index = this.state.files.indexOf(file)

    if (index >= 0) {
      const files = [...this.state.files]
      files.splice(index, 1)
      this.setState({ files })
      this.previews.has(file) && this.previews.delete(file)
    }
  }

  getPreview = file => {
    if (this.previews.has(file)) {
      return this.previews.get(file)
    } else {
      const url = window.URL.createObjectURL(file)
      this.previews.set(file, url)
      return url
    }
  }

  render() {
    const { children, name, accept, multiple, required } = this.props
    return (
      <Relative>
        <input
          ref={this.setInputRef}
          type="file"
          {...inputStyle}
          name={name}
          accept={accept}
          multiple={multiple}
          required={required}
          onChange={this.handleChange}
        />
        {children({
          files: this.state.files,
          openDialog: this.openDialog,
          getPreview: this.getPreview,
          removeFile: this.removeFile,
          clear: this.clear,
        })}
      </Relative>
    )
  }
}
